name: campo_minado
description: Campo Minado.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2


environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_app_name: ^0.1.1


flutter:
  uses-material-design: true

  assets:
     - assets/images/alerta_0.jpeg
     - assets/images/alerta_1.jpeg
     - assets/images/alerta_2.jpeg
     - assets/images/alerta_3.jpeg
     - assets/images/alerta_4.jpeg
     - assets/images/alerta_5.jpeg
     - assets/images/alerta_6.jpeg
     - assets/images/alerta_7.jpeg
     - assets/images/alerta_8.jpeg
     - assets/images/bandeira.jpeg
     - assets/images/bomba.jpeg
     - assets/images/bomba_detonada.jpeg
     - assets/images/fechado.jpeg
     - assets/icons/hard.png
     - assets/icons/medium.png
     - assets/icons/easy.png


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # image_path_ios: "assets/images/launcher/ios.png"
  # image_path_android: "assets/images/launcher/android.png"
  # adaptive_icon_background: "assets/images/launcher/background.png"
  # adaptive_icon_foreground: "assets/images/launcher/android.png"
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 96 # min:48, max:256, default: 48

  # run "flutter pub run flutter_launcher_icons:main" to crate app icons

flutter_app_name:
  name: "Campo minado"

   # run "flutter pub run flutter_app_name" to rename app

# FIM
