name: campo_minado
description: Campo Minado.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1


environment:
  sdk: ">=2.16.2 <3.0.0"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  # image_path_ios: "assets/images/launcher/ios.png"
  # image_path_android: "assets/images/launcher/android.png"
  # adaptive_icon_background: "assets/images/launcher/background.png"
  # adaptive_icon_foreground: "assets/images/launcher/android.png"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
     - assets/images/alerta_0.jpeg
     - assets/images/alerta_1.jpeg
     - assets/images/alerta_2.jpeg
     - assets/images/alerta_3.jpeg
     - assets/images/alerta_4.jpeg
     - assets/images/alerta_5.jpeg
     - assets/images/alerta_6.jpeg
     - assets/images/alerta_7.jpeg
     - assets/images/alerta_8.jpeg
     - assets/images/bandeira.jpeg
     - assets/images/bomba.jpeg
     - assets/images/bomba_detonada.jpeg
     - assets/images/fechado.jpeg
     - assets/icons/hard.png
     - assets/icons/medium.png
     - assets/icons/easy.png

# FIM
